apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: db-transaction-timeout
  namespace: chaos-mesh
  labels:
    experiment_id: "chaos-db-transaction-timeout"
    anomaly_level: "database"
    anomaly_type: "transaction_timeout"
    target_service: "tsdb-mysql"
spec:
  mode: all
  selector:
    namespaces: ["default"]
    labelSelectors:
      app: "tsdb-mysql"
  # No duration = runs until manually stopped
  action: delay
  delay:
    latency: "15s"    # 15 second delay - exceeds typical DB transaction timeout
    jitter: "5s"      # ±5s variation
    correlation: "0"
  direction: to       # Delay responses TO applications FROM database
  target:
    mode: all
    selector:
      namespaces: ["default"]
      expressionSelectors:
        - key: "app"
          operator: In
          values: ["ts-order-service", "ts-preserve-service", "ts-travel-service", "ts-user-service"]
